### ISSUE TITLE
Explore the import function

### ISSUE THREAD

**Issue by leobalter** [leobalter/realms-polyfill#4]
Currently  the `import` function cannot resolve to a module namespace object so it is limited to only resolve to undefined showing when the injection is fulfilled. The injected code should work on globals, which is a bit weak for the API.

**Comment by littledan** [comment]
Resolving to undefined makes sense to me. I like the idea in #8 to have a specific API to import a function in a wrapped way. Maybe this subsumes the need for the `import` API.
